### ISSUE TITLE
Exception on attempting conversion

### ISSUE THREAD

**Issue by michaelmior** [tiarno/plastex#23]
I tried running plastex 1.0.0 and I get the following exception. This breaks even if I use an empty LaTeX file. If I try the Text renderer, I get no exception but also nothing in the output directory.

```
Traceback (most recent call last):
  File "/home/mmior/.pyenv/versions/2.7.10/bin/plastex", line 109, in <module>
    main(sys.argv)
  File "/home/mmior/.pyenv/versions/2.7.10/bin/plastex", line 86, in main
    Renderer().render(document)
  File "/home/mmior/.pyenv/versions/2.7.10/lib/python2.7/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 346, in render
    BaseRenderer.render(self, document)
  File "/home/mmior/.pyenv/versions/2.7.10/lib/python2.7/site-packages/plasTeX/Renderers/__init__.py", line 480, in render
    self.cleanup(document, self.files.values(), postProcess=postProcess)
  File "/home/mmior/.pyenv/versions/2.7.10/lib/python2.7/site-packages/plasTeX/Renderers/XHTML/__init__.py", line 15, in cleanup
    self.doJavaHelpFiles(document, version='1')
  File "/home/mmior/.pyenv/versions/2.7.10/lib/python2.7/site-packages/plasTeX/Renderers/XHTML/__init__.py", line 100, in doJavaHelpFiles
    latexdoc = document.getElementsByTagName('document')[0]
IndexError: list index out of range
```

**Comment by michaelmior** [comment]
Interestingly enough, this does work with `align.tex` and `footnotes.tex` from the unit tests.

**Comment by kesmit13** [comment]
Are you running it on a legal LaTeX document?  If LaTeX won’t compile it, plasTeX won’t either.

Kevin D Smith
Kevin.Smith@octobergray.com

**Comment by michaelmior** [comment]
Yes, it's a legal LaTeX document.

**Comment by kesmit13** [comment]
It looks like your document doesn’t have a ‘document’ environment in it, but without some sort of test case it’s impossible to say.

> On Mar 7, 2016, at 9:26 PM, Michael Mior <notifications@github.com> wrote:
> 
> Yes, it's a legal LaTeX document.
> 
> —
> Reply to this email directly or view it on GitHub.
> 

Kevin Smith
Kevin.Smith@octobergray.com

**Comment by michaelmior** [comment]
There is a document environment. On further inspection, it looks like the issue is with the IEEEtran documentclass. This document correctly compiles, but exhibits the problem under plastex.

```
\documentclass[conference]{IEEEtran}

\begin{document}

\title{Test}

\author{John Doe}

\maketitle

\section{Introduction}

Lorem ipsum

\end{document}
```

**Comment by kesmit13** [comment]
Can you try running the current version of plasTeX in github?  I just ran your test case and it worked for me.

Kevin D Smith
Kevin.Smith@octobergray.com

**Comment by zjing7** [comment]
I have the same problem. Has this been solved?

**Comment by michaelmior** [comment]
@kesmit13 Sorry for the (very) long delay. I gave this a try and it still doesn't work but I get a different error.

```
ERROR: Error while reading argument "#1" of @@@IEEEextracttoken in
   /usr/share/texlive/texmf-dist/tex/latex/IEEEtran/IEEEtran.cls on line 2214
   ('@IEEEextracttokencurgroup' object has no attribute 'catcode')
ERROR: Error while expanding "@@@IEEEextracttoken" in /usr/share/texlive
   /texmf-dist/tex/latex/IEEEtran/IEEEtran.cls on line 2214
   ('@IEEEextracttokencurgroup' object has no attribute 'catcode')
ERROR: Could not load package "IEEEtran": '@IEEEextracttokencurgroup'
   object has no attribute 'catcode'
ERROR: Error while reading argument "#1" of @@@IEEEextracttoken in <tokens>
   on line 1 ('@IEEEextracttokencurgroup' object has no attribute 'catcode')
ERROR: Error while expanding "@@@IEEEextracttoken" in <tokens> on line 1
   ('@IEEEextracttokencurgroup' object has no attribute 'catcode')
ERROR: An error occurred while building the document object in <tokens> on
   line 1 ('@IEEEextracttokencurgroup' object has no attribute 'catcode')
Traceback (most recent call last):
  File "build/scripts-2.7/plastex", line 113, in <module>
    main(sys.argv)
  File "build/scripts-2.7/plastex", line 58, in main
    tex.parse()
  File "/home/mmior/apps/plastex/build/lib/plasTeX/TeX.py", line 426, in parse
    for item in tokens:
  File "/home/mmior/apps/plastex/build/lib/plasTeX/TeX.py", line 46, in next
    return self._next()
  File "/home/mmior/apps/plastex/build/lib/plasTeX/TeX.py", line 335, in __iter__
    tokens = obj.invoke(self)
  File "/home/mmior/apps/plastex/build/lib/plasTeX/__init__.py", line 1065, in invoke
    name='#%s' % len(params)))
  File "/home/mmior/apps/plastex/build/lib/plasTeX/TeX.py", line 596, in readArgument
    return self.readArgumentAndSource(*args, **kwargs)[0]
  File "/home/mmior/apps/plastex/build/lib/plasTeX/TeX.py", line 736, in readArgumentAndSource
    toks, source = self.readToken(expanded, parentNode=parentNode)
  File "/home/mmior/apps/plastex/build/lib/plasTeX/TeX.py", line 795, in readToken
    if t.catcode == Token.CC_BGROUP:
AttributeError: '@IEEEextracttokencurgroup' object has no attribute 'catcode'
```

**Comment by kesmit13** [comment]
The issue is that we don't have an implementation of the IEEEtran document class and it's trying to parse the real LaTeX package which is just too complex.  You may have to add one to your installation.  I would start with just copying plasTeX/Packages/report.py to plasTeX/Packages/IEEEtran.py and seeing how that works.

**Comment by michaelmior** [comment]
@kesmit13 Thanks for the info!
