### ISSUE TITLE
Problem with HTML5 renderer and bibliography

### ISSUE THREAD

**Issue by niklasp** [tiarno/plastex#83]
I have the following tex sample code (which renders without the cite command perfectly)

```
	\section{Conclusions}\label{conclusions}
	There is no longer example which was written by \citet{doe}

	\begin{thebibliography}{9}
	\bibitem[Doe]{doe} \emph{First and last \LaTeX{} example.},
	John Doe 50 B.C.
	\end{thebibliography}
	%\bibliography{ps-wg}
```
However I get the error below. Am I doing it wrong? I am not using the plastex command directly but my own initialization code in python which is basically:

```
	os.chdir('./public')
	c = config
	c += html5config
	document = plasTeX.TeXDocument(config=config)
	document.userdata['working-dir'] = os.getcwd()
	tex = TeX(document, myfile='../testing.tex')
	tex.parse()
	Renderer().render(document)
```
Any advice is appreciated.
```
Traceback (most recent call last):
  File "tex2x.py", line 34, in <module>
    main()
  File "tex2x.py", line 31, in main
    Renderer().render(document)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/PageTemplate/__init__.py", line 381, in render
    BaseRenderer.render(self, document)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/__init__.py", line 497, in render
    str(document)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/PageTemplate/__init__.py", line 52, in renderjinja2
    return tpl.render(tvars)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/PageTemplate/__init__.py", line 52, in renderjinja2
    return tpl.render(tvars)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/PageTemplate/__init__.py", line 52, in renderjinja2
    return tpl.render(tvars)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 4, in top-level template code
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/__init__.py", line 172, in __str__
    val = func(child)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/plasTeX-1.0-py3.5.egg/plasTeX/Renderers/PageTemplate/__init__.py", line 52, in renderjinja2
    return tpl.render(tvars)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 2, in top-level template code
TypeError: 'method' object is not iterable
```

**Comment by PatrickMassot** [comment]
Thanks for the report. I created PR #84 with a quick fix. I'll try to find time for more in depth investigation (I didn't need a bibliography for the project I was working on while creating the HTML5 renderer).

**Comment by niklasp** [comment]
Thank you you both. I am just getting into plastex and it is really satisfying to have a fast issue identifying and solving process.

One note however: As I am working on the python3 branch (isn't it standard yet to use python3?) It would really be awesome to advance work on that branch in order to make it the master branch. Better sooner than later, or the work process of merging the bugfixes is getting more and more later.

How is development on that branch going? What issues remain? Problems? I might have some capacities to contribute.

**Comment by PatrickMassot** [comment]
In principle the python3 branch is up to date (except yesterday when I forgot to fix also this branch). But this is a recent development. There is not yet any release of plasTeX for python3, or any release including the HTML5 renderer. 

There are very few people contributing to plasTeX. As I understand the story, this software was mostly developed 15 years ago by @kesmit13 in order to handle technical documentation at his work. Last year I wanted a TeX to html converter for some [lecture notes](http://www.math.polytechnique.fr/perso/massot.patrick/enseignement/mat553/). PlasTeX came very close to meet my needs and it had the advantage of being written in python, which meant I could hope to contribute extra things I needed. Thanks to plasTeX modular construction, it was rather easy to add an HTML5(+CSS3+JS) renderer, even without understanding much about the core. But only what I needed has been battle tested. I can almost compile my lecture notes using the upstream master branch but not quite. There is still PR #81 pending and I need to wrap up one more PR. But right now I don't need plasTeX and don't have much time.

In the mean time @tiarno also contibuted to plasTeX and, about one year ago, converted it to python3. A few months ago I made sure all developments from the master branch were ported to python3. But we don't have a version which works for both python 2 and python 3.

So, if you have time and energy for plasTeX contributions:
* the easiest way is to use its python3 branch and HTML5 renderer and fill bug reports here. 
* If you have a bit more time you can contribute tests. A low tech but tedious work is to browse the HTML5 or XHTML templates and try to write a LaTeX document using as many supported commands and packages as possible and create a reference pdf that could be compared to an html rendering. If you know about pytest or the UnitTest library you can also contribute automated tests. Currently there are not so many of them (and some of them are actually broken as you can see from the open issues list).
* If you have a lot more time and python skills then you could try to come up with a branch working with both python 2.7 and python 3.4+.
